// Festival list shown on the home screen.
export const festivals = [
  { id: "diwali", name: "Diwali", hook: "Why a whole country lights lamps on one night", date: "Nov 6–10, 2026", meta: "5 regional stories · rituals", icon: "diya", active: true },
  { id: "bhaidooj", name: "Bhai Dooj", hook: "The day Death himself got a sister's blessing", date: "Nov 10, 2026", meta: "Diwali week · 4 regional names", icon: "tilak", active: true },
  { id: "holi", name: "Holi", hook: "One festival, five very different celebrations", date: "Mar 3–4, 2026", meta: "5 regional stories · rituals", icon: "holi", active: true },
  { id: "teej", name: "Teej", hook: "A fast women choose, sing through, and dress up for", date: "Aug 15 & Sep 13–14, 2026", meta: "Sawan season · 3 variants", icon: "bangle", active: true },
  { id: "newyear", name: "The New Year Cluster", hook: "One spring moment, celebrated under eight different names", date: "Mar 19 – Apr 15, 2026", meta: "8 regions · rituals", icon: "sun", active: true },
  { id: "ganesh", name: "Ganesh Chaturthi", hook: "How a clay idol became a ten-day city festival", date: "TBD", meta: "In production", icon: "steam", active: false },
  { id: "navratri", name: "Navratri", hook: "Nine nights, nine forms of the goddess", date: "TBD", meta: "In production", icon: "holi", active: false },
  { id: "onam", name: "Onam", hook: "The king who comes home once a year", date: "TBD", meta: "In production", icon: "steam", active: false },
  { id: "pongal", name: "Pongal", hook: "A harvest festival told through a pot of rice", date: "TBD", meta: "In production", icon: "steam", active: false },
];

// Full Stories + Rituals content, keyed by festival id.
export const storyData = {
  diwali: {
    title: "Diwali",
    dateRange: "Nov 6–10, 2026",
    sky: "radial-gradient(circle at 30% 20%, #2E2158, #150C2B 70%)",
    regions: [
      { name: "Uttar Pradesh", date: "Nov 8, 2026 (Lakshmi Puja night)", text: "The most widely told origin: after fourteen years of exile, Rama, Sita and Lakshmana return to Ayodhya having defeated the demon king Ravana. The Ramayana says the city's people lit rows of earthen lamps to guide them home through the dark new-moon night — and light became the festival's defining symbol. Ayodhya still marks this literally: in 2023, over 22 lakh diyas were lit along the Sarayu river in a single night, a record-setting Deepotsav. Every diya lit elsewhere in India today traces back, in spirit, to that one homecoming.", source: "Valmiki Ramayana; Ayodhya Deepotsav records, 2023" },
      { name: "Bengal", date: "Nov 8, 2026 (Kali Puja night)", text: "While most of India lights lamps for Lakshmi, goddess of wealth, Bengal spends the same night worshipping Kali — the fierce, protective form of the divine feminine. The tradition was popularised in the 18th century by Raja Krishnachandra of Nadia, and later deepened by the mystic Ramakrishna, who worshipped Kali as the Supreme Mother at Dakshineswar. The evening before, families light fourteen lamps in a ritual called Bhoot Chaturdashi, believed to guide ancestral spirits home. Red hibiscus offerings and fierce imagery reflect a different idea: that facing the darkness, not just lighting it away, is its own form of devotion.", source: "Historical accounts of Raja Krishnachandra; Ramakrishna Mission records" },
      { name: "Tamil Nadu", date: "Nov 7, 2026 (Naraka Chaturdashi)", text: "Called Deepavali here, and marked a day before the northern festival, the story centres on Krishna rather than Rama — his defeat of the demon Narakasura, who had held thousands captive. Families wake before sunrise for Ganga Snanam, a ritual oil bath with warm sesame oil said to wash away the demon's blood and, symbolically, the year's negativity. Homes are marked with kolam at the doorstep, and a spiced digestive called deepavali marundhu is eaten to brace the body for a day of sweets. Only after the bath do crackers, new clothes and family visits begin.", source: "Tamil Nadu oral tradition; regional Naraka Chaturdashi accounts" },
      { name: "Gujarat", date: "Nov 8–9, 2026", text: "For Gujarat's trading communities, Diwali marks the close of the financial year as much as the Ramayana's ending. Merchants perform Chopda Pujan: old ledgers are closed and new ones opened before Goddess Lakshmi, inscribed with 'Shubh' and 'Labh' — auspiciousness and profit — and marked with a swastika for a prosperous year ahead. The day after Diwali is Bestu Varas, the Gujarati New Year, greeted with 'Saal Mubarak.' In a state built on merchant heritage, the festival of lights doubles as an annual audit, wrapped in ritual instead of paperwork.", source: "Vikram Samvat calendar records; Gujarati trade-community custom" },
      { name: "Maharashtra", date: "Nov 7–10, 2026", text: "Maharashtra's Diwali opens days earlier with Vasu Baras, when families worship a cow and her calf as a symbol of maternal care. The morning after is Abhyang Snan — a pre-dawn oil massage with fragrant ubtan, followed by a bath before sunrise, still announced in many homes with the old rhyme 'Utha utha Diwali ali, Moti snanachi vel zali.' Kitchens turn out faral all week — chakli, karanji, chivda, laddu. The festival closes on Bhaubeej, when sisters perform aarti for their brothers.", source: "Maharashtra Tourism records; Marathi household oral tradition" },
    ],
    rituals: [{
      heading: "Lakshmi–Ganesha Puja",
      deity: "Goddess Lakshmi, worshipped alongside Lord Ganesha",
      when: "Main Diwali evening, after sunset (Pradosh Kaal)",
      samagri: ["Idols or a picture of Lakshmi & Ganesha", "Diyas & oil/ghee", "Kumkum, haldi, akshat (rice)", "Fresh flowers & a garland", "Sweets & fruit for the offering", "A silver or copper coin", "Rangoli materials for the entrance"],
      steps: [
        "Clean and light the home — Lakshmi is said to enter only clean, well-lit spaces.",
        "Set a red cloth on a small platform and place the Lakshmi-Ganesha idols or picture on it.",
        "Light a diya and incense, then take a short sankalp (a spoken intention for the puja).",
        "Offer kumkum, haldi, rice and flowers to the idols, one at a time.",
        "Offer sweets and fruit as naivedya (a food offering).",
        "Recite the mantra, then perform aarti — circling a lit diya before the idols.",
        "Distribute the offered sweets (prasad) to the family.",
      ],
      mantra: { sanskrit: "ॐ श्रीं महालक्ष्म्यै नमः", translit: "Om Shreem Mahalakshmyai Namah", meaning: "A short invocation to Goddess Lakshmi for wealth, wellbeing and grace." },
      attire: { clothing: "New or freshly washed clothes — women often choose a saree or festive ethnic wear", colors: "Red, yellow, gold and pink are considered auspicious; black is generally avoided", why: "New clothes mark a fresh start; bright, warm colours are believed to invite prosperity rather than repel it." },
      significance: "The puja isn't only devotional — it's a household ritual of renewal: clearing out the old, welcoming the new, and marking the home as ready for the year ahead.",
    }],
  },

  holi: {
    title: "Holi",
    dateRange: "Mar 3–4, 2026 (regional stories span late Feb–late Mar)",
    sky: "radial-gradient(circle at 30% 20%, #4A2350, #1E1030 70%)",
    regions: [
      { name: "Braj (Mathura)", date: "Feb 25–26, 2026", text: "In Krishna's home region, Holi begins over a week early with Lathmar Holi. Legend has it that a young Krishna would travel from Nandgaon to tease Radha and her friends in Barsana; the women drove him off with sticks in response. Every year since, that teasing is replayed literally — women from Barsana 'beat' visiting men from Nandgaon with wooden lathis while the men shield themselves, and the roles reverse in Nandgaon the next day.", source: "Wikipedia — Lathmar Holi; Barsana temple accounts" },
      { name: "West Bengal", date: "Mar 3, 2026 (Dol Purnima)", text: "In Bengal, Holi is Dol Jatra — but Shantiniketan, the university town founded by Rabindranath Tagore, celebrates it as Basanta Utsav, a spring festival he formally introduced in 1923. Students and teachers greet each other with dry abir instead of drenching one another in colour and water, dance and sing Rabindra Sangeet, and wear palash flowers in their hair.", source: "Visva-Bharati University records, Shantiniketan" },
      { name: "Punjab", date: "Mar 4–6, 2026", text: "The day after Holi, Punjab's Sikh community holds a very different festival at Anandpur Sahib: Hola Mohalla. Founded by Guru Gobind Singh in 1701, it replaces colour-throwing with mock battles — Nihang Sikhs demonstrate Gatka swordsmanship, tent-pegging and bareback horse riding.", source: "Takht Sri Anandpur Sahib historical records" },
      { name: "Manipur", date: "~Mar 3–8, 2026 (approx.)", text: "The Meitei people of Manipur call it Yaosang — a name rooted in agrarian life, marking winter's end long before Holi's colours were folded in through Vaishnavism in the 1700s. Its best-loved custom is Thabal Chongba, a moonlit circle dance that, in more conservative eras, was one of the only settings where young men and women could mix freely.", source: "Live History India; regional Manipur cultural records" },
      { name: "Konkan (Maharashtra)", date: "Mar 15–29, 2026", text: "Along the Konkan coast, Holi becomes Shimga (Shigmo in Goa) — less a single day of colour, more a week-plus of village life on display. Deities are carried from temple to home in decorated palanquins called palkhis, in processions accompanied by dhol drummers and folk theatre forms like Tamasha and Dashavatar.", source: "Maharashtra Tourism records; Konkan folk tradition" },
    ],
    rituals: [
      {
        heading: "The night before: Holika Dahan",
        deity: "Symbolically Holika & Prahlad, with prayers offered to Lord Vishnu and Agni (fire)",
        when: "Evening of Phalguna Purnima — the full moon night before Holi",
        samagri: ["Wood, dried twigs & cow-dung cakes for the pyre", "A bowl of water", "Roli and unbroken rice (akshat)", "Raw cotton thread (moli)", "Grains, coconut & sweets to offer to the fire"],
        steps: [
          "Bathe and wear clean or new clothes before the ritual.",
          "Sit facing east or north; sprinkle water on yourself and the puja items.",
          "Wrap the moli thread around the wood pile three or seven times, clockwise.",
          "Light the pyre at the muhurat — this represents Holika burning while Prahlad's faith keeps him safe.",
          "Walk around the fire (parikrama), traditionally seven times, offering grains and sweets into it.",
        ],
        mantra: { sanskrit: "ॐ पुण्डरीकाक्षः पुनातु", translit: "Om Pundarikakshah Punatu", meaning: "An invocation to Vishnu, 'the lotus-eyed one,' for purification, chanted before the fire is lit." },
        significance: "A solemn, fire-lit ritual about good outlasting evil — the emotional opposite of the free-for-all that follows the next morning.",
      },
      {
        heading: "The next day: Rangwali Holi",
        deity: "None — a community celebration rather than a puja",
        when: "The following morning, once the colours come out",
        attire: { clothing: "Old or white clothes — a plain kurta-pyjama is traditional, so colour shows clearly", colors: "Every colour, deliberately — gulal, water colours, sometimes flower petals in temple towns", why: "White is a blank canvas, and the point of the day is precisely to not stay clean — a rare, sanctioned break from everyday order." },
        significance: "Colour, water and closeness between people who might not otherwise touch or joke together the rest of the year.",
      },
    ],
  },

  bhaidooj: {
    title: "Bhai Dooj",
    dateRange: "Nov 10, 2026",
    sky: "radial-gradient(circle at 30% 20%, #3A2A50, #170F2E 70%)",
    regions: [
      { name: "Maharashtra", date: "Nov 10, 2026", text: "Called Bhau Beej here, the ritual is the same tilak-and-aarti core as elsewhere, but the day is built around a feast — sisters invite their brothers over and cook their favourite dishes, often including basundi-poori or puran poli.", source: "Regional festival records; Marathi household oral tradition" },
      { name: "West Bengal", date: "Nov 10, 2026", text: "Known as Bhai Phonta, the tilak itself changes — sisters use a sandalwood paste rather than plain roli, applying it while reciting a protective verse for their brother. No thali is considered complete without khaja, a sugar-glazed sweet unique to the day.", source: "Regional festival records" },
      { name: "Uttar Pradesh & Bihar", date: "Nov 10, 2026", text: "Here it's Bhai Tika, and the tilak is five-coloured rather than a single mark — each colour said to add its own layer of protection against evil for the year ahead.", source: "Regional festival records" },
      { name: "South India", date: "Nov 10, 2026", text: "Known as Bhagini Hastha Bhojanam — literally, 'a meal from a sister's hand' — the day drops the tilak ceremony almost entirely. The ritual is the meal itself.", source: "Regional festival records" },
    ],
    rituals: [{
      heading: "The tilak ceremony",
      deity: "No idol — the brother is treated as the day's honoured figure, with the Yama-Yamuna legend as its reference point",
      when: "Second day of Kartik Shukla Paksha, the last day of Diwali's five-day cycle",
      samagri: ["A puja thali with roli/kumkum, rice (akshat) and a diya", "Sweets prepared by the sister", "A coconut, in some regions", "A gift from the brother"],
      steps: [
        "The sister prepares a thali and seats her brother facing east or north.",
        "She lights the diya and applies tilak — roli and rice — to his forehead.",
        "She performs a short aarti, circling the lit diya before him.",
        "She feeds him a sweet by hand while reciting the verse or a wish for his long life.",
        "The brother gives a gift and, traditionally, renews his promise to look out for her.",
      ],
      mantra: { sanskrit: "गंगा पूजे यमुना को, यमी पूजे यमराज को, गंगा-यमुना नीर बहे, मेरे भाई की आयु बढ़े", translit: "Ganga puje Yamuna ko, Yami puje Yamraj ko, Ganga-Yamuna neer bahe, mere bhai ki aayu badhe", meaning: "A folk verse invoking the rivers Ganga and Yamuna, and Yami blessing Yamraj — asking for the brother's life to be long." },
      significance: "The legend deliberately casts Death himself receiving a sister's blessing. Regional names vary (Bhai Phonta, Bhau Beej, Bhai Tika, Bhagini Hastha Bhojanam) but the ritual core — tilak, a meal, a gift — stays remarkably consistent.",
    }],
  },

  teej: {
    title: "Teej",
    dateRange: "Aug 15 & Sep 13–14, 2026",
    sky: "radial-gradient(circle at 30% 20%, #1E3A2E, #0F1F17 70%)",
    regions: [
      { name: "Rajasthan (Jaipur)", date: "Aug 15, 2026 (Hariyali Teej)", text: "Jaipur turns Hariyali Teej into a state occasion: the Teej Mata ki Sawari, a royal procession, carries a gilded idol of Parvati through the old city on decorated elephants and camels, accompanied by Ghoomar dancers and folk bands.", source: "Rajasthan Tourism Department records" },
      { name: "Uttar Pradesh & Bihar", date: "Aug 15, 2026 (Hariyali Teej)", text: "Alongside the fast, married women receive Sindhara — a gift of sweets, clothes and bangles sent from their parental home to their in-laws' house in the days before Teej.", source: "Regional festival records" },
      { name: "Hartalika Teej (a month later)", date: "Sep 13–14, 2026", text: "A stricter cousin of Hariyali Teej, observed in Bhadrapada rather than Shravan. The fast here is nirjala — no water at all — and red or yellow is worn instead of Hariyali Teej's green. In 2026 it lands on the same date as Ganesh Chaturthi, so several regions observe it a day earlier, on 13 September.", source: "Regional festival records; comparative Teej accounts" },
    ],
    rituals: [{
      heading: "The Teej vrat (fast)",
      deity: "Goddess Parvati, worshipped alongside Lord Shiva",
      when: "Third day of Shukla Paksha in Shravan — Hartalika Teej follows a month later in Bhadrapada",
      samagri: ["Idol or picture of Shiva-Parvati", "Bel patra (bael leaves) and dhatura flowers", "Green bangles and mehendi (henna)", "Sindoor, akshat rice and a ghee lamp", "Sweets for the offering and to close the fast"],
      steps: [
        "Wake before sunrise and take a sankalp — a spoken vow to keep the fast.",
        "Dress in green, having applied mehendi the evening before or that morning.",
        "Set up Shiva-Parvati images, offering bel patra, dhatura and flowers.",
        "Sit with other women to hear or read the Teej vrat katha.",
        "Chant the mantra, traditionally 108 times, keeping count on a mala.",
        "Keep either a nirjala fast (no water) or a sajal fast (water permitted) — a lighter fruit-only fast is common for health reasons.",
        "Break the fast after moonrise or the closing puja, sharing prasad with family.",
      ],
      mantra: { sanskrit: "ॐ उमायै नमः", translit: "Om Umayai Namah", meaning: "'I bow to Uma' — Uma is another name for Parvati." },
      attire: { clothing: "Green sarees or suits, green bangles, and solah shringar (sixteen traditional adornments)", colors: "Green for Hariyali Teej; red or yellow for Hartalika Teej a month on", why: "Green stands for the monsoon's new growth and fertility." },
      significance: "The fast is real and can be demanding, but it's framed less as deprivation and more as something women choose, sing about, dress up for, and do together.",
    }],
  },

  newyear: {
    title: "The New Year Cluster",
    dateRange: "Mar 19 – Apr 15, 2026",
    sky: "radial-gradient(circle at 30% 20%, #3A2E10, #1A1508 70%)",
    regions: [
      { name: "Maharashtra (Gudi Padwa)", date: "Mar 19, 2026", text: "Marathi and Konkani households mark the day by raising a gudi — a bamboo pole dressed in bright cloth, neem and mango leaves, a sugar-crystal garland, and an upturned copper pot on top. Some trace it to Lord Brahma recreating the universe on this day; others to Rama's return to Ayodhya, or to Shivaji's forces raising victory flags after battle.", source: "Maharashtra Tourism records; regional festival accounts" },
      { name: "Karnataka, Andhra Pradesh & Telangana (Ugadi)", date: "Mar 19, 2026", text: "The exact same lunar day is Ugadi here, and it opens with Ugadi Pachadi — a dish deliberately combining six tastes eaten together in one sitting, as a lesson that the year ahead will hold all of these and none should be refused. Later, communities gather to hear Panchanga Shravanam, the new almanac read aloud by a pandit.", source: "Regional festival accounts; Panchanga Shravanam tradition" },
      { name: "Kerala (Vishu)", date: "Apr 15, 2026", text: "Kerala's version follows the solar calendar rather than the lunar one. The defining ritual is Vishukkani — 'that which is seen first' — a tray of rice, fruit, gold, a mirror and yellow konna flowers, which children are led to with covered eyes so their first sight of the new year is deliberately auspicious.", source: "Regional festival accounts; Kerala tourism records" },
      { name: "Tamil Nadu (Puthandu)", date: "Apr 14, 2026", text: "Tamil Nadu's own new year runs on a similar principle to Vishu — a Kani, an arranged first sight of fruit, flowers, gold and a mirror. A raw-mango-and-jaggery dish is eaten for the same six-taste logic as Ugadi's pachadi.", source: "Regional festival accounts" },
      { name: "Assam (Bohag/Rongali Bihu)", date: "Apr 14–15, 2026 (approx.)", text: "Assam's new year opens not with a deity, but with cattle. On Goru Bihu, cows and bulls are led to a river, washed with a turmeric-and-black-gram paste, garlanded, and fed jaggery. Only the next day, Manuh Bihu, turns to people.", source: "Regional festival accounts; Assam agrarian tradition" },
      { name: "West Bengal (Poila Boishakh)", date: "Apr 14 (Bangladesh) / Apr 15, 2026 (West Bengal)", text: "Poila Boishakh is celebrated by Bengali Hindus and Muslims alike, which makes it more a shared cultural new year than a strictly religious one. Traders perform Halkhata, closing an old ledger and opening a fresh red one with customers over sweets.", source: "Regional festival accounts; UNESCO Intangible Cultural Heritage records" },
      { name: "Sindhi community (Cheti Chand)", date: "Mar 19, 2026", text: "Sindhi Hindus mark the same lunar day as the birthday of Jhulelal — an avatar of Varuna, the water god. After a forty-day prayer period called Chaliho, families carry Behrana Sahib — a dough mound representing Jhulelal — to a river in a singing, dancing procession before immersing it.", source: "Regional festival accounts; Sindhi Hindu tradition" },
      { name: "Punjab (Baisakhi)", date: "Apr 14, 2026", text: "For Punjab's farming communities, the same date marks the wheat harvest — fields are cut, bonfires lit, and bhangra and gidda danced. The day carries a second, separate layer of meaning for Sikhs specifically: the founding of the Khalsa Panth by Guru Gobind Singh in 1699.", source: "Regional festival accounts; Sikh historical records" },
    ],
    rituals: [
      { heading: "Maharashtra — Gudi Padwa", deity: "No idol — the gudi itself is the day's central object", when: "Chaitra Shukla Pratipada", samagri: ["A bamboo pole", "Bright silk or cotton cloth", "Neem and mango leaves", "A garland and an upturned copper or silver pot", "Neem-jaggery mixture to eat afterward"], steps: ["Wake before sunrise, bathe, and wear new clothes.", "Decorate the doorstep with rangoli.", "Assemble the gudi and raise it outside the home or from a window.", "Pray before it as a family.", "Eat the neem-jaggery mixture, then share puran poli or shrikhand."], significance: "No fixed mantra here — the ritual speaks entirely through the object itself." },
      { heading: "Karnataka, Andhra Pradesh & Telangana — Ugadi", deity: "Household deities generally, rather than one specific to the day", when: "Same day as Gudi Padwa", samagri: ["Neem flowers", "Raw mango", "Tamarind", "Jaggery", "Salt and green chilli", "The new year's Panchanga (almanac)"], steps: ["Bathe and clean the home before sunrise.", "Prepare Ugadi Pachadi by mixing all six ingredients together.", "Offer a portion to the household deities before anyone eats.", "Eat the pachadi as the first thing of the day.", "Gather to hear the Panchanga Shravanam."], significance: "The six-taste dish is treated as more important than any spoken prayer." },
      { heading: "Kerala — Vishu", deity: "Lord Krishna, with the Vishukkani arrangement as the focus", when: "First day of the Malayalam month of Medam", samagri: ["An uruli (brass vessel)", "Raw rice, a coconut, cucumber and fruit", "Gold jewellery and a mirror (valkannadi)", "Kanikkonna flowers", "A lit nilavilakku (oil lamp)", "Coins for kaineettam"], steps: ["The night before, arrange the Vishukkani facing east, beside a lit lamp and an image of Krishna.", "On waking, walk to the kani with eyes closed, and open them only in front of it.", "Offer a short prayer to Krishna.", "Elders give kaineettam to younger family members.", "Close the day with Vishu Sadya, a feast on a banana leaf."], significance: "What you see first shapes the year, so the ritual engineers that first sight rather than relying on a spoken mantra." },
      { heading: "Tamil Nadu — Puthandu", deity: "Household deities, viewed as part of the Kani arrangement", when: "First day of the Tamil month of Chithirai", samagri: ["Fruits, betel leaves and flowers", "Gold jewellery and a mirror", "Raw mango and jaggery (for maanga pachadi)", "Rice and coins", "A lit lamp"], steps: ["Clean the home and draw kolam the evening before.", "Arrange the Kani before a lamp.", "View the Kani first thing in the morning.", "Prepare and eat maanga pachadi.", "Visit a temple and exchange 'Puthandu Vazhthukal.'"], significance: "Nearly identical in logic to Vishu next door." },
      { heading: "Assam — Bohag/Rongali Bihu", deity: "None — an agrarian festival honouring cattle and the land", when: "Multi-day, opening on the last day of Chot into Bohag", samagri: ["A paste of turmeric and black gram (maah-halodhi)", "Gourd and brinjal for garlanding cattle", "Jaggery and green grass to feed them", "New gamosa and clothes for Manuh Bihu"], steps: ["On Goru Bihu, lead cattle to a river and bathe them.", "Apply the turmeric-black gram paste and garland them.", "Feed them jaggery and grass, replacing old ropes.", "The next day, bathe, wear new clothes, and visit elders.", "Join Husori — young people visiting homes to sing Bihu songs."], significance: "The absence of a deity or mantra is the point — this is thanks directed at animals and land, not a request made to a god." },
      { heading: "West Bengal — Poila Boishakh", deity: "None core to the day; some Hindu families add a Lakshmi-Ganesha puja separately", when: "First day of Boishakh, Bengali solar calendar", samagri: ["A new red ledger, for Halkhata", "Sweets to offer customers and guests", "Traditional dress"], steps: ["Traders close the old ledger and open a new one (Halkhata).", "Sweets are distributed as part of the ceremony.", "Families wear traditional dress and visit relatives.", "Communities join the Mangal Shobhajatra procession.", "Some Hindu households add a separate Lakshmi-Ganesha puja."], significance: "Its core ritual is commercial and cultural, not religious — worth being upfront about rather than presenting it as Hindu-only." },
      { heading: "Sindhi community — Cheti Chand", deity: "Jhulelal (an avatar of Varuna, the water god)", when: "Chaitra Shukla Pratipada — same day as Gudi Padwa", samagri: ["A bronze thali with rice, sugar and kumkum", "Dough shaped into a mound representing Jhulelal", "Cloves and cardamom as symbolic ornaments", "An idol or image of Jhulelal", "A wheat-flour lamp with five wicks (Jyot Jagan)"], steps: ["Shape the Behrana and decorate it with kumkum, cloves and cardamom.", "Carry it, with a Jhulelal idol, in procession to a river, singing and dancing.", "Light the Jyot Jagan lamp at the water's edge.", "Immerse the Behrana in the water.", "Sing Pallav and distribute prasad."], significance: "The procession itself is treated as the prayer." },
      { heading: "Punjab — Baisakhi (the harvest side)", deity: "No deity central to the agrarian observance", when: "Mid-April, coinciding with the wheat harvest", samagri: ["The ripened wheat crop itself", "Wood for the evening bonfire", "Dhol drums for bhangra and gidda"], steps: ["Cut the first of the ripened wheat.", "Visit a gurdwara or temple.", "Gather at village fairs (melas).", "Light a bonfire in the evening.", "Dance bhangra and gidda late into the night."], significance: "A harvest thanksgiving. Its more well-known religious meaning — the founding of the Khalsa Panth — belongs specifically to Sikh tradition and is worth keeping distinct." },
    ],
  },
};
